### ISSUE TITLE
Melhorar actions

### ISSUE THREAD

**Issue by diegogriep** [concretesolutions/tecla-sap#5]

**Comment by joao-felipe-santoro** [comment]
Minha sugestão: 
- Criar um workflow que executa lint, testes e qualquer outra coisa com relação a saúde do código em cima de pull requests e pushes pra na branch main. 
- Criar um workflow que efetua o deploy nos pushes pra branch main. 

qualquer coisa dá uma olhada aqui: https://github.com/concretesolutions/cs-links-api/tree/master/.github/workflows

**Comment by joao-felipe-santoro** [comment]
Pull Request #18 aberto pra resolver isso :)
